### PR TITLE
Fea/add new member/aclub

### PR DESCRIPTION
**Pull request by jovianch**

### CODE REVIEW

**Comment by alsoncahyadi** [comment]
Please resolve conflict!

**Comment by alsoncahyadi** [comment]
Please resolve conflict! @jovianch

**Comment by jovianch** [comment]
resolved @alsoncahyadi

**Comment by alsoncahyadi** [comment]
Please resolve it!
@jovianch

**Comment by alsoncahyadi** [comment]
Nice! Merging!

**Pull request merged**
